name: agofoods
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^2.0.0
  geolocator: ^7.0.3
  geocoding: ^2.0.0
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  get: ^4.6.6
  flutter_vector_icons: ^2.0.0
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  flutter_hooks: ^0.20.3
  flutter_boxicons: ^3.2.0
  font_awesome_flutter: ^10.6.0
  http: ^1.2.0
  shimmer: ^3.0.0
  glass: ^1.0.2+1
  flutter_svg: ^2.0.9
  lottie: ^3.0.0
  get_storage: ^2.1.1
  webview_flutter: ^4.5.0
  webview_flutter_android: ^3.12.1
  webview_flutter_wkwebview: ^3.9.4
  device_preview: ^1.1.0
  otp_text_field: ^1.1.3
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  country_picker: ^2.0.23
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/anime/
    - assets/icons/

